/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mmccall.coordsdb;

import org.bukkit.Server;
import org.bukkit.command.CommandMap;
import org.bukkit.plugin.java.JavaPlugin;

import dev.mmccall.coordsdb.cmd.Get;
import dev.mmccall.coordsdb.cmd.List;
import dev.mmccall.coordsdb.cmd.Set;

public class CoordsDB extends JavaPlugin {

    Server server;
    CommandMap commandMap;

    @Override
    public void onEnable() {
        server = this.getServer();
        commandMap = server.getCommandMap();

        DB.load();

        commandMap.register("coords", new Set());
        commandMap.register("coords", new Get());
        commandMap.register("coords", new List());
    }

    @Override
    public void onDisable() {
        // TODO Auto-generated method stub
    }
}
