/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mmccall.coordsdb;

import org.bukkit.plugin.java.JavaPlugin;

import dev.mmccall.coordsdb.cmd.Query;
import dev.mmccall.coordsdb.cmd.Del;
import dev.mmccall.coordsdb.cmd.Set;

public class CoordsDB extends JavaPlugin {

    @Override
    public void onEnable() {
        DB.load();

        this.getCommand("set").setExecutor(new Set());
        this.getCommand("query").setExecutor(new Query());
        this.getCommand("del").setExecutor(new Del());
    }

    @Override
    public void onDisable() {
        // TODO Auto-generated method stub
    }
}
